Areas/Admin/Controllers/OrderADController.cs
using BackEnd_Project.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BackEnd_Project.Areas.Admin.Controllers;

[Area("Admin")]
public class OrderADController : Controller
{
    private readonly SportStoreDb2Context _context;

    public OrderADController(SportStoreDb2Context context)
    {
        _context = context;
    }
    
    public IActionResult Index()
    {
        var orders = _context.Orders.ToList();
        return View(orders);
    }

    // chi tiet

    public async Task<IActionResult> Details(int? id)
    {
        if (id == null) return NotFound("Order ID is missing.");

        // lay thong tin dua tren order
        var order = await _context.Orders
            .Include(o => o.OrderDetails)
            .ThenInclude(od => od.Product)
            .Include(o => o.User) // Bao gồm thông tin người dùng
            .FirstOrDefaultAsync(o => o.OrderId == id);

        if (order == null) return NotFound("Order not found.");
        
        return View(order);
    }
    
    [HttpGet]
    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Create(Order order)
    {
        _context.Add(order);
        await _context.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
    }

    
    // GET: /Order/Edit/5
    public IActionResult Edit(int? id)
    {
        if (id == null) return NotFound();

        var order = _context.Orders
            .Include(o => o.OrderDetails)
            .ThenInclude(od => od.Product)
            .FirstOrDefault(o => o.OrderId == id);

        if (order == null) return NotFound();

        return View(order);
    }

    // POST: /Order/Edit/5
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, Order order)
    {
        if (id != order.OrderId) return NotFound();

                _context.Update(order);
                await _context.SaveChangesAsync();
         
            return RedirectToAction(nameof(Index));
    }
    
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Delete(int id)
    {
        var order = await _context.Orders.FindAsync(id);
        if (order == null) return NotFound();

        _context.Orders.Remove(order);
        await _context.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
    }
    
    
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> ConfirmOrder(int id)
    {
        var order = await _context.Orders.FindAsync(id);
        if (order == null) return NotFound();

        if (order.OrderStatus == "Chờ xác nhận")
        {
            order.OrderStatus = "Đang giao";
            _context.Update(order);
            await _context.SaveChangesAsync();
        }

        return RedirectToAction("Index", "Admin");
    }

    // Hiển thị danh sách đơn hàng theo trạng thái
    public IActionResult OrdersByStatus(string status)
    {
        var orders = _context.Orders.Where(o => o.OrderStatus == status).ToList();
        return View("Index", orders);
    }

}

Areas/Admin/Views/OrderAD/Create.cshtml
@model Order

@{
    ViewData["Title"] = "Create";
    Layout = "_LayoutAdmin";
}

<div class="container">
    <h1>Create New Order</h1>
    <form asp-action="Create" method="post">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

        <div class="form-group">
            <label asp-for="UserId" class="control-label">UserID</label>
            <input asp-for="UserId" class="form-control"/>
            <span asp-validation-for="UserId" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="OrderStatus" class="control-label">OrderStatus</label>
            <input asp-for="OrderStatus" class="form-control"/>
            <span asp-validation-for="OrderStatus" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="TotalAmount" class="control-label">TotalAmount</label>
            <input asp-for="TotalAmount" class="form-control"/>
            <span asp-validation-for="TotalAmount" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="OrderDate" class="control-label">OrderDate</label>
            <input asp-for="OrderDate" type="datetime-local" class="form-control"/>
            <span asp-validation-for="OrderDate" class="text-danger"></span>
        </div>

        <div class="form-group">
            <input type="submit" value="Create" class="btn btn-primary"/>
        </div>
    </form>
</div>

@section Scripts {
    <script>
        document.addEventListener('DOMContentLoaded', (event) => {
            var now = new Date();
            var day = ('0' + now.getDate()).slice(-2);
            var month = ('0' + (now.getMonth() + 1)).slice(-2);
            var today = now.getFullYear() + '-' + (month) + '-' + (day);
            var hours = ('0' + now.getHours()).slice(-2);
            var minutes = ('0' + now.getMinutes()).slice(-2);
            var formattedTime = today + 'T' + hours + ':' + minutes;
            document.getElementById('OrderDate').value = formattedTime;
        });
    </script>
}

Areas/Admin/Views/OrderAD/Details.cshtml
@using System.Globalization
@model Order 
@{
    ViewData["Title"] = "Order Detail";
    Layout = "_LayoutAdmin";
}
<div class="container mt-5">
    <h2 class="mb-4">Order Confirmation</h2>

    <div class="card mb-4">
        <div class="card-header">
            Order Details
        </div>
        <div class="card-body">
            <h5 class="card-title">Order #@Model.OrderId</h5>
            <p class="card-text">
                <strong>Date:</strong> @Model.OrderDate.ToString("dd/MM/yyyy")
            </p>
            <p class="card-text">
                <strong>Total Amount:</strong> @Model.TotalAmount.ToString("C", new CultureInfo("vi-VN"))
            </p>
            <p class="card-text">
                <strong>Status:</strong> @Model.OrderStatus
            </p>
            <p class="card-text">
                <strong>Shipping Method:</strong> @Model.ShippingMethod
            </p>
            <p class="card-text">
                <strong>Payment Method:</strong> @Model.PaymentMethod
            </p>
            <p class="card-text">
                <strong>Shipping Address:</strong> @Model.ShippingAddress
            </p>
        </div>
    </div>

    <div class="card mb-4">
        <div class="card-header">
            User Information
        </div>
        <div class="card-body">
            <h5 class="card-title">@Model.User.FullName</h5>
            <p class="card-text">
                <strong>Email:</strong> @Model.User.Email
            </p>
            <p class="card-text">
                <strong>Phone:</strong> @Model.User.PhoneNumber
            </p>
            <p class="card-text">
                <strong>Address:</strong> @Model.User.Address
            </p>
        </div>
    </div>

    <div class="card">
        <div class="card-header">
            Order Items
        </div>
        <div class="card-body">
            <table class="table">
                <thead>
                <tr>
                    <th scope="col">Product</th>
                    <th scope="col">Quantity</th>
                    <th scope="col">Unit Price</th>
                    <th scope="col">Total</th>
                </tr>
                </thead>
                <tbody>
                @foreach (var item in Model.OrderDetails)
                {
                    <tr>
                        <td>@item.Product.Name</td>
                        <td>@item.Quantity</td>
                        <td>@item.UnitPrice.ToString("C", new CultureInfo("vi-VN"))</td>
                        @{
                            var totalPrice = (item.Quantity * item.UnitPrice).ToString("C", new CultureInfo("vi-VN"));
                        }
                        <td>@totalPrice</td>
                    </tr>
                }
                </tbody>
            </table>
        </div>
    </div>
</div>

Areas/Admin/Views/OrderAD/Edit.cshtml
@model BackEnd_Project.Models.Order

@{
    ViewData["Title"] = "Edit Order";
    Layout = "_LayoutAdmin";
}
<div class="col-md-8 m-auto">
    <h2 class="text-center font-weight-bold">Edit Product</h2>

<h4>Order</h4>
<hr />
<div class="row">
    <div class="col-12">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="OrderId" />

            <div class="form-group">
                <label asp-for="UserId" class="control-label"></label>
                <input asp-for="UserId" class="form-control" />
                <span asp-validation-for="UserId" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="OrderDate" class="control-label"></label>
                <input asp-for="OrderDate" class="form-control" />
                <span asp-validation-for="OrderDate" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="TotalAmount" class="control-label"></label>
                <input asp-for="TotalAmount" class="form-control" />
                <span asp-validation-for="TotalAmount" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="OrderStatus" class="control-label"></label>
                <input asp-for="OrderStatus" class="form-control" />
                <span asp-validation-for="OrderStatus" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="ShippingMethod" class="control-label"></label>
                <input asp-for="ShippingMethod" class="form-control" />
                <span asp-validation-for="ShippingMethod" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="PaymentMethod" class="control-label"></label>
                <input asp-for="PaymentMethod" class="form-control" />
                <span asp-validation-for="PaymentMethod" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="ShippingAddress" class="control-label"></label>
                <input asp-for="ShippingAddress" class="form-control" />
                <span asp-validation-for="ShippingAddress" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>
</div>

Areas/Admin/Views/OrderAD/Index.cshtml
@model List<Order>

@{
    ViewData["Title"] = "Order Page";
    Layout = "_LayoutAdmin";
}

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h2>Orders</h2>
            <p>
                <a href="@Url.Action("Create")" class="btn btn-primary">Create New</a>
                <div class="btn-group" role="group" aria-label="Order Status">
                    <a href="@Url.Action("Index")" class="btn btn-secondary">Tất cả</a>
                    <a href="@Url.Action("OrdersByStatus", new { status = "Chờ xác nhận" })" class="btn btn-primary">Chờ xác nhận</a>
                    <a href="@Url.Action("OrdersByStatus", new { status = "Đang giao" })" class="btn btn-warning">Đang giao</a>
                    <a href="@Url.Action("OrdersByStatus", new { status = "Đã huỷ" })" class="btn btn-danger">Đã hủy</a>
                </div>
            </p>
            <table class="table table-striped">
                <thead>
                <tr>
                    <th>Order ID</th>
                    <th>Order Date</th>
                    <th>Total Amount</th>
                    <th>Order Status</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>
                @foreach (var order in Model)
                {
                    <tr>
                        <td>@order.OrderId</td>
                        <td>@order.OrderDate</td>
                        <td>@order.TotalAmount</td>
                        <td>@order.OrderStatus</td>
                        <td>
                            <div class="btn-group" role="group" aria-label="Order Actions">
                              <a href="@Url.Action("Details", new { id = order.OrderId })" class="btn btn-info btn-sm">Details</a>
                                                             <a href="@Url.Action("Edit", new { id = order.OrderId })" class="btn btn-warning btn-sm">Edit</a>
                                                             <form asp-action="Delete" asp-route-id="@order.OrderId" method="post" onsubmit="return confirm('Are you sure you want to delete this order?');" style="display: inline-block;">
                                                                 <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                                                             </form>
                                                             @if (order.OrderStatus == "Chờ xác nhận")
                                                             {
                                                                 <form asp-action="ConfirmOrder" asp-controller="OrderAD" method="post" style="display: inline-block;">
                                                                     <input type="hidden" name="id" value="@order.OrderId"/>
                                                                     <button type="submit" class="btn btn-primary btn-sm">Xác nhận</button>
                                                                 </form>
                                                             }

                            </div>


                        </td>
                    </tr>
                }
                </tbody>
            </table>
        </div>
    </div>
</div>